### PR TITLE
fix(free): prevent server flooding after 5xx

### LINKED ISSUE #136: Exponential backoff for sleeps
We should increase the time as the number of requests increases.

_Originally posted by @Satont in https://github.com/grammyjs/storages/pull/135#discussion_r1048348484_

Most likely, it's a good idea to double the time to wait with each attempt, capped at one hour.

### PR DESCRIPTION
**Pull request by KnorpelSenf**
If a 5xx error occurs regularly, we must not retry immediately. This could cause millions of requests in short periods of time.

Closes #136

### CODE REVIEW

File: packages/free/src/adapter.ts [hunk 1]
```diff
@@ -108,7 +108,12 @@ async function retryFetch(
     res = await fetch(...args);
     if (res.status >= 500) {
       console.error(`${res.status} in free session service, retrying!`);
+      await sleep(3000);
```
Comment (Satont) [inline packages/free/src/adapter.ts:111]: Is such a big sleep needed there?

Comment (KnorpelSenf) [reply packages/free/src/adapter.ts:111]: What else do you suggest?

Comment (Satont) [reply packages/free/src/adapter.ts:111]: > What else do you suggest?

Increase the time as the number of requests increases. Or do you not like this approach?

Comment (KnorpelSenf) [reply packages/free/src/adapter.ts:111]: Yes, we can do that. Linearly? Quadratically? Exponentially?

Comment (Satont) [reply packages/free/src/adapter.ts:111]: > Yes, we can do that. Linearly? Quadratically? Exponentially?

Thats up to you.

Comment (KnorpelSenf) [reply packages/free/src/adapter.ts:111]: https://t.me/grammyjs/99895

Comment (KnorpelSenf) [reply packages/free/src/adapter.ts:111]: See #136

**Review by Satont — APPROVED** [review]
LGTM 👍🏻
